name: Build & publish changed images

on:
  push:
    branches:
      - dev
      - master
    paths:
      - "images/**/**"
  workflow_dispatch:

jobs:
  # Note: When modifying this job, copy modifications to all other workflows' image jobs.
  changed_base_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: remote-apps
            source_directory: remote-apps
            source_files_for_diff: remote-apps

    name: ${{ matrix.name }}${{ matrix.version_suffix }} image build & publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # This is for changed-files.
          submodules: ${{ matrix.submodules }}

      - name: Check for changes to ${{ matrix.name }} image source
        id: check
        uses: tj-actions/changed-files@v1.1.2
        with:
          files: ${{ matrix.source_files_for_diff }}

      - name: Build & publish ${{ matrix.name }} image
        if: steps.check.outputs.any_changed == 'true' || steps.check.outputs.any_deleted == 'true'
        uses: ./.github/actions/build_and_publish_image
        with:
          github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: ${{ github.actor }}
          image_name: ${{ matrix.name }}
          image_source_directory: ${{ matrix.source_directory }}
          image_version_1: ${{ github.ref_name }}${{ matrix.version_suffix }}

  changed_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: xpra
            source_directory: .
            submodules: recursive
            source_files_for_diff: .
            build_args: REMOTE_APPS_IMAGE=ghcr.io/selkies-project/selkies-xpra/remote-apps:${{ github.ref_name }}

    name: ${{ matrix.name }}${{ matrix.version_suffix }} image build & publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # This is for changed-files.
          submodules: ${{ matrix.submodules }}

      - name: Check for changes to ${{ matrix.name }} image source
        id: check
        uses: tj-actions/changed-files@v1.1.2
        with:
          files: ${{ matrix.source_files_for_diff }}

      - name: Build & publish ${{ matrix.name }} image
        if: steps.check.outputs.any_changed == 'true' || steps.check.outputs.any_deleted == 'true'
        uses: ./.github/actions/build_and_publish_image
        with:
          github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: ${{ github.actor }}
          image_name: ${{ matrix.name }}
          image_source_directory: ${{ matrix.source_directory }}
          image_version_1: ${{ github.ref_name }}${{ matrix.version_suffix }}
          build_args: ${{ matrix.build_args }}