name: Publish release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  # Note: When modifying this job, copy modifications to all other workflows' image jobs.
  base_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: remote-apps
            source_directory: remote-apps

          - name: xpra
            source_directory: .
            submodules: recursive

    name: ${{ matrix.name }}${{ matrix.version_suffix }} image build & publish
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: ${{ matrix.submodules }}

      - name: Build & publish ${{ matrix.name }} image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: ${{ github.actor }}
          image_name: ${{ matrix.name }}
          image_source_directory: ${{ matrix.source_directory }}
          image_version_1: ${{ github.ref_name }}_1${{ matrix.version_suffix }}
          image_version_2: latest${{ matrix.version_suffix }}

  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: xpra
            source_directory: .
            submodules: recursive
            build_args: REMOTE_APPS_IMAGE=ghcr.io/selkies-project/selkies-xpra/remote-apps:${{ github.ref_name }}

    name: ${{ matrix.name }}${{ matrix.version_suffix }} image build & publish
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: ${{ matrix.submodules }}

      - name: Build & publish ${{ matrix.name }} image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: ${{ github.actor }}
          image_name: ${{ matrix.name }}
          image_source_directory: ${{ matrix.source_directory }}
          image_version_1: ${{ github.ref_name }}_1${{ matrix.version_suffix }}
          image_version_2: latest${{ matrix.version_suffix }}
          build_args: ${{ matrix.build_args }}

  create_release:
    needs: all_images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          release_name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
